-- ------------------------------------------------------------------
-- Title: Test.
-- Notes: cap_leak_index/analysis/sql/test.sql 
--        cap_leak_index, 20190511 NYU Datathon
--        eICU Collaborative Research Database v2.0.
-- ------------------------------------------------------------------
